{
    'name':'solar hub management',
    'version':'18.0',
    'author':"krishnaveni and sri sathya",
    'depends':['hr','contacts','mail',],
    'data': [
        'security/ir.model.access.csv',
        'views/solaremployee.xml',
        'views/view_customer.xml',
        'views/solarpanel.xml',
        'views/battery.xml',
        'views/inverter.xml',
        'views/solarhub_product_template.xml',
        'data/ir_sequence.xml',
        'views/service_type.xml',
        'views/property_type.xml',
        'views/assurance_type.xml',
        'views/assurance_subtype.xml',
        'views/tax.xml',
        "views/contact_diary.xml",
        "views/notice_board.xml",
        'views/menu.xml',

    ],
}